name: bdta_env               
dependencies:
  - python=3.12              
  - jupyter
  - ipykernel
  - pandas                
  - matplotlib               
  - seaborn                  
  - scikit-learn             
  - kagglehub
  - pip
  - pip:
    - opendatasets
    - fairlearn