name: bdta_env               
dependencies:
  - python=3.12              # Fissa la versione di Python
  - jupyter                  # Per il server notebook
  - ipykernel                # Per collegarlo a VS Code
  - pandas                   # Per i dati
  - matplotlib               # Per i grafici
  - seaborn                  # Per grafici pi√π belli
  - scikit-learn             # Per il machine learning
  - pip                      # Pip serve per installare cose che non esistono su Conda
  - pip:
    - opendatasets           # Esempio: librerie che trovi solo su pip